require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'spec/fixtures/**/*'


Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma


Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'  # Allow long comments

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented


Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 250

Metrics/ModuleLength:
  Max: 250

Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12


RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false
